### ISSUE TITLE
Build Error on fresh install : config.h not found

### ISSUE THREAD

**Issue by thylo** [viromedia/ViroARSampleApp#10]
Hello,

I'm trying to get Viro (and this sample) running as a separate IOS application without any luck for the past few hours...

Steps to reproduce : 
- OSX, node v10.8.0, homebrew v1.8.4, react-native-cli v2.0.1, Xcode v10.01
- clone this repo
- run `yarn install`
- run `yarn start`
- run `./setup-ide.sh --ios`
- opening `./ios/ViroSample.xcworkspace` in Xcode
- changing the package name for Target ViroSampleAR to `be.thylo.ViroSampleAR`
- assign me in the signing fields
- hit build -> iPhone 8
- tried to set ios 10 as target without luck

Build Error :

`'config.h' file not found`

in file included from :
/Users/julienmoreau/code/experiments/ViroARSampleApp/node_modules/react-native/third-party/glog-0.3.4/src/utilities.cc:32:10: In file included from /Users/julienmoreau/code/experiments/ViroARSampleApp/node_modules/react-native/third-party/glog-0.3.4/src/utilities.cc:32:

in file included from :
/Users/julienmoreau/code/experiments/ViroARSampleApp/node_modules/react-native/third-party/glog-0.3.4/src/utilities.h:73:10: In file included from /Users/julienmoreau/code/experiments/ViroARSampleApp/node_modules/react-native/third-party/glog-0.3.4/src/utilities.h:73:

**Comment by VikAdvani** [comment]
Hi @thylo,
This is react native issue here being tracked here: https://github.com/facebook/react-native/issues/19774

To fix it simply run the following from your project root(where your node_modules directory is in your project):
```
 cd ./node_modules/react-native/third-party/glog-0.3.4 && ../../scripts/ios-configure-glog.sh
```

Running the above command on your terminal should fix it.

**Comment by thylo** [comment]
@VikAdvani thanks your response. Saddly it still won't build.

`ld: framework not found AWSCore
clang: error: linker command failed with exit code 1 (use -v to see invocation)`. If it's a react-native error I'll search that way...

**Comment by VikAdvani** [comment]
Hi @thylo, I'm unable to reproduce the issue you are experiencing on iOS. This sounds like a possible cocoapods issue. What version of cocoapods are you using? We recommend using version 1.5 or greater. You can find out what version you are by running:
```pod --version``` from the terminal. 

If your pod version is under 1.5, I'd recommend upgrading and rerunning the setup-ide script.

Also are you running on a device or a simulator? If you are running on the simulator try a device to see if the issue still occurs.

**Comment by ghost** [comment]
I was having this problem and my cocoa pods version is 1.5.3. I fixed it by following
@VikAdvani 's answer
https://github.com/viromedia/ViroARSampleApp/issues/10#issuecomment-445320538
and afterwards had an issue I solved with
https://github.com/facebook/react-native/issues/19569#issuecomment-422691829
